// Cosmetic ingredient database — INCI names and CAS numbers
// Sources: CosIng (EU), PCPC INCI Dictionary, PubChem, supplier specifications
// Trade name → INCI name + CAS number mapping

export const ingredientDB = [
  // ── Water / Solvents ─────────────────────────────────────────────────────────
  { trade_name: "Water", inci: "Aqua", cas: "7732-18-5", function: "Solvent" },
  { trade_name: "Purified Water", inci: "Aqua", cas: "7732-18-5", function: "Solvent" },
  { trade_name: "Deionized Water", inci: "Aqua", cas: "7732-18-5", function: "Solvent" },
  { trade_name: "Ethanol", inci: "Alcohol Denat.", cas: "64-17-5", function: "Solvent/Preservative" },
  { trade_name: "Isopropanol", inci: "Isopropyl Alcohol", cas: "67-63-0", function: "Solvent" },
  { trade_name: "Propylene Glycol", inci: "Propylene Glycol", cas: "57-55-6", function: "Humectant/Solvent" },
  { trade_name: "Butylene Glycol", inci: "Butylene Glycol", cas: "107-88-0", function: "Humectant/Solvent" },
  { trade_name: "Pentylene Glycol", inci: "Pentylene Glycol", cas: "5343-92-0", function: "Humectant/Preservative Booster" },
  { trade_name: "Hexylene Glycol", inci: "Hexylene Glycol", cas: "107-41-5", function: "Humectant/Solvent" },
  { trade_name: "Caprylyl Glycol", inci: "Caprylyl Glycol", cas: "1117-86-8", function: "Humectant/Preservative Booster" },

  // ── Humectants ────────────────────────────────────────────────────────────────
  { trade_name: "Glycerin", inci: "Glycerin", cas: "56-81-5", function: "Humectant" },
  { trade_name: "Glycerol", inci: "Glycerin", cas: "56-81-5", function: "Humectant" },
  { trade_name: "Sorbitol", inci: "Sorbitol", cas: "50-70-4", function: "Humectant" },
  { trade_name: "Mannitol", inci: "Mannitol", cas: "69-65-8", function: "Humectant" },
  { trade_name: "Xylitol", inci: "Xylitol", cas: "87-99-0", function: "Humectant" },
  { trade_name: "Hyaluronic Acid", inci: "Sodium Hyaluronate", cas: "9067-32-7", function: "Humectant/Anti-aging" },
  { trade_name: "Sodium Hyaluronate", inci: "Sodium Hyaluronate", cas: "9067-32-7", function: "Humectant/Anti-aging" },
  { trade_name: "Hyafix", inci: "Sodium Hyaluronate", cas: "9067-32-7", supplier: "Lucas Meyer", function: "Humectant" },
  { trade_name: "Hyalufix", inci: "Sodium Hyaluronate", cas: "9067-32-7", function: "Humectant" },
  { trade_name: "Panthenol", inci: "Panthenol", cas: "81-13-0", function: "Humectant/Conditioning" },
  { trade_name: "DL-Panthenol", inci: "Panthenol", cas: "81-13-0", function: "Humectant/Conditioning" },
  { trade_name: "Allantoin", inci: "Allantoin", cas: "97-59-6", function: "Soothing/Keratolytic" },
  { trade_name: "Urea", inci: "Urea", cas: "57-13-6", function: "Humectant/Keratolytic" },
  { trade_name: "Sodium PCA", inci: "Sodium PCA", cas: "28874-51-3", function: "Humectant" },
  { trade_name: "Lactic Acid", inci: "Lactic Acid", cas: "50-21-5", function: "pH Adjuster/AHA/Humectant" },
  { trade_name: "Glycolic Acid", inci: "Glycolic Acid", cas: "79-14-1", function: "Exfoliant/pH Adjuster" },
  { trade_name: "Betaine", inci: "Betaine", cas: "107-43-7", function: "Humectant/Surfactant" },

  // ── Fatty Alcohols ────────────────────────────────────────────────────────────
  { trade_name: "Cetyl Alcohol", inci: "Cetyl Alcohol", cas: "36653-82-4", function: "Emollient/Emulsifier/Thickener" },
  { trade_name: "Stearyl Alcohol", inci: "Stearyl Alcohol", cas: "112-92-5", function: "Emollient/Emulsifier/Thickener" },
  { trade_name: "Cetearyl Alcohol", inci: "Cetearyl Alcohol", cas: "67762-27-0", function: "Emollient/Emulsifier/Thickener" },
  { trade_name: "Behenyl Alcohol", inci: "Behenyl Alcohol", cas: "661-19-8", function: "Emollient/Thickener" },
  { trade_name: "Lauryl Alcohol", inci: "Lauryl Alcohol", cas: "112-53-8", function: "Emollient" },
  { trade_name: "Myristyl Alcohol", inci: "Myristyl Alcohol", cas: "112-72-1", function: "Emollient" },

  // ── Fatty Acids ───────────────────────────────────────────────────────────────
  { trade_name: "Stearic Acid", inci: "Stearic Acid", cas: "57-11-4", function: "Emollient/Thickener/Emulsifier" },
  { trade_name: "Palmitic Acid", inci: "Palmitic Acid", cas: "57-10-3", function: "Emollient/Thickener" },
  { trade_name: "Myristic Acid", inci: "Myristic Acid", cas: "544-63-8", function: "Emollient/Surfactant" },
  { trade_name: "Lauric Acid", inci: "Lauric Acid", cas: "143-07-7", function: "Emollient/Surfactant" },
  { trade_name: "Oleic Acid", inci: "Oleic Acid", cas: "112-80-1", function: "Emollient" },
  { trade_name: "Linoleic Acid", inci: "Linoleic Acid", cas: "60-33-3", function: "Emollient/Skin Conditioning" },

  // ── Waxes ─────────────────────────────────────────────────────────────────────
  { trade_name: "Beeswax", inci: "Beeswax", cas: "8012-89-3", function: "Emollient/Thickener/Film Former" },
  { trade_name: "Carnauba Wax", inci: "Copernicia Cerifera Cera", cas: "8015-86-9", function: "Thickener/Film Former" },
  { trade_name: "Candelilla Wax", inci: "Euphorbia Cerifera Cera", cas: "8006-44-8", function: "Thickener/Film Former" },
  { trade_name: "Microcrystalline Wax", inci: "Microcrystalline Wax", cas: "63231-60-7", function: "Thickener/Film Former" },
  { trade_name: "Paraffin Wax", inci: "Paraffin", cas: "8002-74-2", function: "Thickener/Emollient" },
  { trade_name: "Ozokerite", inci: "Ozokerite", cas: "8021-55-4", function: "Thickener/Binder" },
  { trade_name: "Ceresin", inci: "Ceresin", cas: "8001-75-0", function: "Thickener/Binder" },

  // ── Esters / Emollients ───────────────────────────────────────────────────────
  { trade_name: "Isopropyl Myristate", inci: "Isopropyl Myristate", cas: "110-27-0", function: "Emollient/Solvent" },
  { trade_name: "Isopropyl Palmitate", inci: "Isopropyl Palmitate", cas: "142-91-6", function: "Emollient" },
  { trade_name: "Isopropyl Stearate", inci: "Isopropyl Stearate", cas: "112-10-7", function: "Emollient" },
  { trade_name: "Cetiol CC", inci: "Dicaprylyl Carbonate", cas: "1680-31-5", supplier: "BASF", function: "Emollient/Skin Feel Modifier" },
  { trade_name: "Cetiol C5", inci: "Coco-Caprylate/Caprate", cas: "72576-80-8", supplier: "BASF", function: "Emollient" },
  { trade_name: "Cetiol OE", inci: "Dicaprylyl Ether", cas: "629-82-3", supplier: "BASF", function: "Emollient" },
  { trade_name: "Cetiol SN", inci: "Cetearyl Isononanoate", cas: "95077-99-9", supplier: "BASF", function: "Emollient" },
  { trade_name: "Cetiol HE", inci: "PEG-7 Glyceryl Cocoate", cas: "65381-09-1", supplier: "BASF", function: "Emollient/Emulsifier" },
  { trade_name: "Myritol 318", inci: "Caprylic/Capric Triglyceride", cas: "73398-61-5", supplier: "BASF", function: "Emollient/Carrier Oil" },
  { trade_name: "Caprylic/Capric Triglyceride", inci: "Caprylic/Capric Triglyceride", cas: "73398-61-5", function: "Emollient/Carrier" },
  { trade_name: "MCT Oil", inci: "Caprylic/Capric Triglyceride", cas: "73398-61-5", function: "Emollient/Carrier" },
  { trade_name: "Ethylhexyl Palmitate", inci: "Ethylhexyl Palmitate", cas: "29806-73-3", function: "Emollient" },
  { trade_name: "Cetyl Palmitate", inci: "Cetyl Palmitate", cas: "540-10-3", function: "Emollient/Thickener" },
  { trade_name: "Jojoba Oil", inci: "Simmondsia Chinensis Seed Oil", cas: "61789-91-1", function: "Emollient/Skin Conditioning" },
  { trade_name: "Argan Oil", inci: "Argania Spinosa Kernel Oil", cas: "223747-87-3", function: "Emollient/Skin Conditioning" },
  { trade_name: "Rosehip Oil", inci: "Rosa Canina Fruit Oil", cas: "84696-47-9", function: "Emollient/Skin Conditioning" },
  { trade_name: "Sweet Almond Oil", inci: "Prunus Amygdalus Dulcis Oil", cas: "8013-76-1", function: "Emollient" },
  { trade_name: "Avocado Oil", inci: "Persea Gratissima Oil", cas: "8024-32-6", function: "Emollient" },
  { trade_name: "Sunflower Oil", inci: "Helianthus Annuus Seed Oil", cas: "8001-21-6", function: "Emollient" },
  { trade_name: "Olive Oil", inci: "Olea Europaea Fruit Oil", cas: "8001-25-0", function: "Emollient" },
  { trade_name: "Coconut Oil", inci: "Cocos Nucifera Oil", cas: "8001-31-8", function: "Emollient" },
  { trade_name: "Mineral Oil", inci: "Paraffinum Liquidum", cas: "8042-47-5", function: "Emollient/Occlusif" },
  { trade_name: "Petrolatum", inci: "Petrolatum", cas: "8009-03-8", function: "Emollient/Occlusif" },
  { trade_name: "Squalane", inci: "Squalane", cas: "111-01-3", function: "Emollient" },
  { trade_name: "Neossance Squalane", inci: "Squalane", cas: "111-01-3", supplier: "Givaudan", function: "Emollient" },

  // ── Silicones ─────────────────────────────────────────────────────────────────
  { trade_name: "Dimethicone", inci: "Dimethicone", cas: "9006-65-9", function: "Emollient/Skin Conditioning" },
  { trade_name: "Cyclomethicone", inci: "Cyclomethicone", cas: "69430-24-6", function: "Emollient/Carrier" },
  { trade_name: "Cyclopentasiloxane", inci: "Cyclopentasiloxane", cas: "541-02-6", function: "Emollient/Carrier" },
  { trade_name: "Cyclohexasiloxane", inci: "Cyclohexasiloxane", cas: "540-97-6", function: "Emollient/Carrier" },
  { trade_name: "Dimethiconol", inci: "Dimethiconol", cas: "31692-79-2", function: "Emollient/Shine" },
  { trade_name: "Phenyl Trimethicone", inci: "Phenyl Trimethicone", cas: "2116-84-9", function: "Emollient/Shine" },
  { trade_name: "Amodimethicone", inci: "Amodimethicone", cas: "71750-79-3", function: "Hair Conditioning" },
  { trade_name: "DC 200 Fluid", inci: "Dimethicone", cas: "9006-65-9", supplier: "Dow", function: "Emollient" },
  { trade_name: "DC 245 Fluid", inci: "Cyclopentasiloxane", cas: "541-02-6", supplier: "Dow", function: "Emollient/Carrier" },

  // ── Thickeners / Rheology Modifiers ──────────────────────────────────────────
  { trade_name: "Carbopol 940", inci: "Carbomer", cas: "9003-01-4", supplier: "Lubrizol", function: "Thickener/Gelling Agent" },
  { trade_name: "Carbopol 941", inci: "Carbomer", cas: "9003-01-4", supplier: "Lubrizol", function: "Thickener" },
  { trade_name: "Carbopol 980", inci: "Carbomer", cas: "9003-01-4", supplier: "Lubrizol", function: "Thickener/Gelling Agent" },
  { trade_name: "Carbopol 981", inci: "Carbomer", cas: "9003-01-4", supplier: "Lubrizol", function: "Thickener" },
  { trade_name: "Carbopol ETD 2020", inci: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", cas: "9062-04-8", supplier: "Lubrizol", function: "Thickener" },
  { trade_name: "Carbopol Ultrez 10", inci: "Carbomer", cas: "9003-01-4", supplier: "Lubrizol", function: "Thickener/Gelling Agent" },
  { trade_name: "Carbopol Ultrez 20", inci: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", cas: "9062-04-8", supplier: "Lubrizol", function: "Thickener" },
  { trade_name: "Carbopol Ultrez 21", inci: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", cas: "9062-04-8", supplier: "Lubrizol", function: "Thickener" },
  { trade_name: "Pemulen TR-1", inci: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", cas: "9062-04-8", supplier: "Lubrizol", function: "Emulsifier/Thickener" },
  { trade_name: "Pemulen TR-2", inci: "Acrylates/C10-30 Alkyl Acrylate Crosspolymer", cas: "9062-04-8", supplier: "Lubrizol", function: "Emulsifier/Thickener" },
  { trade_name: "Sepigel 305", inci: "Polyacrylamide (and) C13-14 Isoparaffin (and) Laureth-7", cas: "9003-05-8", supplier: "Seppic", function: "Thickener/Gelling Agent" },
  { trade_name: "Sepimax Zen", inci: "Polyacrylate Crosspolymer-6", cas: "1612891-46-5", supplier: "Seppic", function: "Thickener/Gelling Agent" },
  { trade_name: "Simulgel NS", inci: "Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer (and) Squalane (and) Polysorbate 60", cas: "-", supplier: "Seppic", function: "Thickener/Emulsifier" },
  { trade_name: "Simulgel EG", inci: "Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer (and) Isohexadecane (and) Polysorbate 80", cas: "-", supplier: "Seppic", function: "Thickener/Emulsifier" },
  { trade_name: "Xanthan Gum", inci: "Xanthan Gum", cas: "11138-66-2", function: "Thickener/Stabilizer" },
  { trade_name: "Hydroxyethylcellulose", inci: "Hydroxyethylcellulose", cas: "9004-62-0", function: "Thickener" },
  { trade_name: "Natrosol 250 HHR", inci: "Hydroxyethylcellulose", cas: "9004-62-0", supplier: "Ashland", function: "Thickener" },
  { trade_name: "Hydroxypropyl Methylcellulose", inci: "Hydroxypropyl Methylcellulose", cas: "9004-65-3", function: "Thickener/Film Former" },
  { trade_name: "HPMC", inci: "Hydroxypropyl Methylcellulose", cas: "9004-65-3", function: "Thickener" },
  { trade_name: "Methylcellulose", inci: "Methylcellulose", cas: "9004-67-5", function: "Thickener/Film Former" },
  { trade_name: "Sodium CMC", inci: "Cellulose Gum", cas: "9004-32-4", function: "Thickener/Stabilizer" },
  { trade_name: "Carboxymethylcellulose", inci: "Cellulose Gum", cas: "9004-32-4", function: "Thickener/Stabilizer" },
  { trade_name: "Sodium Alginate", inci: "Sodium Alginate", cas: "9005-38-3", function: "Thickener/Gelling Agent" },
  { trade_name: "Carrageenan", inci: "Carrageenan", cas: "9000-07-1", function: "Thickener/Gelling Agent" },
  { trade_name: "Guar Gum", inci: "Guar Gum", cas: "9000-30-0", function: "Thickener" },
  { trade_name: "Locust Bean Gum", inci: "Ceratonia Siliqua Gum", cas: "9000-40-2", function: "Thickener" },
  { trade_name: "Gelatin", inci: "Hydrolyzed Collagen", cas: "9000-70-8", function: "Film Former/Thickener" },

  // ── Emulsifiers ───────────────────────────────────────────────────────────────
  { trade_name: "Polysorbate 20", inci: "Polysorbate-20", cas: "9005-64-5", function: "Emulsifier/Solubilizer" },
  { trade_name: "Polysorbate 60", inci: "Polysorbate-60", cas: "9005-67-8", function: "Emulsifier" },
  { trade_name: "Polysorbate 80", inci: "Polysorbate-80", cas: "9005-65-6", function: "Emulsifier/Solubilizer" },
  { trade_name: "Tween 20", inci: "Polysorbate-20", cas: "9005-64-5", function: "Emulsifier/Solubilizer" },
  { trade_name: "Tween 60", inci: "Polysorbate-60", cas: "9005-67-8", function: "Emulsifier" },
  { trade_name: "Tween 80", inci: "Polysorbate-80", cas: "9005-65-6", function: "Emulsifier/Solubilizer" },
  { trade_name: "Span 20", inci: "Sorbitan Laurate", cas: "1338-39-2", function: "Emulsifier" },
  { trade_name: "Span 60", inci: "Sorbitan Stearate", cas: "1338-41-6", function: "Emulsifier" },
  { trade_name: "Span 80", inci: "Sorbitan Oleate", cas: "1338-43-8", function: "Emulsifier" },
  { trade_name: "Sorbitan Stearate", inci: "Sorbitan Stearate", cas: "1338-41-6", function: "Emulsifier" },
  { trade_name: "Glyceryl Stearate", inci: "Glyceryl Stearate", cas: "123-94-4", function: "Emulsifier/Emollient" },
  { trade_name: "Glyceryl Monostearate", inci: "Glyceryl Stearate", cas: "123-94-4", function: "Emulsifier/Emollient" },
  { trade_name: "GMS", inci: "Glyceryl Stearate", cas: "123-94-4", function: "Emulsifier" },
  { trade_name: "Emulgin B2", inci: "Ceteareth-20", cas: "68439-49-6", supplier: "BASF", function: "Emulsifier" },
  { trade_name: "Ceteareth-20", inci: "Ceteareth-20", cas: "68439-49-6", function: "Emulsifier" },
  { trade_name: "Ceteareth-12", inci: "Ceteareth-12", cas: "68439-49-6", function: "Emulsifier" },
  { trade_name: "PEG-100 Stearate", inci: "PEG-100 Stearate", cas: "9004-99-3", function: "Emulsifier" },
  { trade_name: "PEG-40 Stearate", inci: "PEG-40 Stearate", cas: "9004-99-3", function: "Emulsifier" },
  { trade_name: "Arlacel 165", inci: "Glyceryl Stearate (and) PEG-100 Stearate", cas: "123-94-4", supplier: "Croda", function: "Emulsifier" },
  { trade_name: "Tego Emulse 1221", inci: "Cetearyl Glucoside (and) Cetearyl Alcohol", cas: "246159-33-1", supplier: "Evonik", function: "Emulsifier" },
  { trade_name: "Olivem 1000", inci: "Cetearyl Olivate (and) Sorbitan Olivate", cas: "-", function: "Emulsifier" },
  { trade_name: "BTMS-50", inci: "Behentrimonium Methosulfate (and) Cetearyl Alcohol", cas: "81646-13-1", function: "Emulsifier/Conditioner" },
  { trade_name: "Incroquat BTMS-50", inci: "Behentrimonium Methosulfate (and) Cetearyl Alcohol", cas: "81646-13-1", supplier: "Croda", function: "Emulsifier/Conditioner" },
  { trade_name: "Lecithin", inci: "Lecithin", cas: "8002-43-5", function: "Emulsifier/Skin Conditioning" },

  // ── Preservatives ─────────────────────────────────────────────────────────────
  { trade_name: "Phenoxyethanol", inci: "Phenoxyethanol", cas: "122-99-6", function: "Preservative" },
  { trade_name: "Methylparaben", inci: "Methylparaben", cas: "99-76-3", function: "Preservative" },
  { trade_name: "Propylparaben", inci: "Propylparaben", cas: "94-13-3", function: "Preservative" },
  { trade_name: "Ethylparaben", inci: "Ethylparaben", cas: "120-47-8", function: "Preservative" },
  { trade_name: "Butylparaben", inci: "Butylparaben", cas: "94-26-8", function: "Preservative" },
  { trade_name: "Sodium Benzoate", inci: "Sodium Benzoate", cas: "532-32-1", function: "Preservative" },
  { trade_name: "Potassium Sorbate", inci: "Potassium Sorbate", cas: "24634-61-5", function: "Preservative" },
  { trade_name: "Sorbic Acid", inci: "Sorbic Acid", cas: "110-44-1", function: "Preservative" },
  { trade_name: "Benzoic Acid", inci: "Benzoic Acid", cas: "65-85-0", function: "Preservative/pH Adjuster" },
  { trade_name: "DMDM Hydantoin", inci: "DMDM Hydantoin", cas: "6440-58-4", function: "Preservative" },
  { trade_name: "Imidazolidinyl Urea", inci: "Imidazolidinyl Urea", cas: "39236-46-9", function: "Preservative" },
  { trade_name: "Diazolidinyl Urea", inci: "Diazolidinyl Urea", cas: "78491-02-8", function: "Preservative" },
  { trade_name: "Chlorphenesin", inci: "Chlorphenesin", cas: "104-29-0", function: "Preservative" },
  { trade_name: "Chlorhexidine Digluconate", inci: "Chlorhexidine Digluconate", cas: "18472-51-0", function: "Preservative/Antimicrobial" },
  { trade_name: "Benzyl Alcohol", inci: "Benzyl Alcohol", cas: "100-51-6", function: "Preservative/Solvent" },
  { trade_name: "Dehydroacetic Acid", inci: "Dehydroacetic Acid", cas: "520-45-6", function: "Preservative" },
  { trade_name: "Euxyl K 903", inci: "Phenoxyethanol (and) Ethylhexylglycerin", cas: "122-99-6", supplier: "Schülke", function: "Preservative" },
  { trade_name: "Euxyl K 940", inci: "Phenoxyethanol (and) Ethylhexylglycerin", cas: "122-99-6", supplier: "Schülke", function: "Preservative" },
  { trade_name: "Optiphen", inci: "Phenoxyethanol (and) Caprylyl Glycol", cas: "122-99-6", supplier: "Ashland", function: "Preservative" },
  { trade_name: "Optiphen Plus", inci: "Phenoxyethanol (and) Caprylyl Glycol (and) Sorbic Acid", cas: "122-99-6", supplier: "Ashland", function: "Preservative" },
  { trade_name: "Geogard 111", inci: "Benzyl Alcohol (and) Salicylic Acid (and) Glycerin (and) Sorbic Acid", cas: "100-51-6", supplier: "Lonza", function: "Preservative" },
  { trade_name: "Geogard ECT", inci: "Benzyl Alcohol (and) Salicylic Acid (and) Glycerin (and) Sorbic Acid", cas: "100-51-6", supplier: "Lonza", function: "Preservative" },
  { trade_name: "Liquid Germall Plus", inci: "Propylene Glycol (and) Diazolidinyl Urea (and) Iodopropynyl Butylcarbamate", cas: "57-55-6", function: "Preservative" },
  { trade_name: "Kathon CG", inci: "Methylchloroisothiazolinone (and) Methylisothiazolinone", cas: "26172-55-4", function: "Preservative" },
  { trade_name: "Bronopol", inci: "Bronopol", cas: "52-51-7", function: "Preservative" },
  { trade_name: "Ethylhexylglycerin", inci: "Ethylhexylglycerin", cas: "70445-33-9", function: "Preservative Booster/Humectant" },

  // ── Surfactants ───────────────────────────────────────────────────────────────
  { trade_name: "Sodium Lauryl Sulfate", inci: "Sodium Lauryl Sulfate", cas: "151-21-3", function: "Surfactant/Detergent" },
  { trade_name: "SLS", inci: "Sodium Lauryl Sulfate", cas: "151-21-3", function: "Surfactant/Detergent" },
  { trade_name: "Sodium Laureth Sulfate", inci: "Sodium Laureth Sulfate", cas: "9004-82-4", function: "Surfactant/Detergent" },
  { trade_name: "SLES", inci: "Sodium Laureth Sulfate", cas: "9004-82-4", function: "Surfactant/Detergent" },
  { trade_name: "Ammonium Lauryl Sulfate", inci: "Ammonium Lauryl Sulfate", cas: "2235-54-3", function: "Surfactant/Foaming" },
  { trade_name: "Ammonium Laureth Sulfate", inci: "Ammonium Laureth Sulfate", cas: "32612-48-9", function: "Surfactant/Foaming" },
  { trade_name: "Cocamidopropyl Betaine", inci: "Cocamidopropyl Betaine", cas: "61789-40-0", function: "Surfactant/Foam Booster" },
  { trade_name: "CAPB", inci: "Cocamidopropyl Betaine", cas: "61789-40-0", function: "Surfactant/Foam Booster" },
  { trade_name: "Cocamide DEA", inci: "Cocamide DEA", cas: "68603-42-9", function: "Foam Booster/Thickener" },
  { trade_name: "Cocamide MEA", inci: "Cocamide MEA", cas: "68140-00-1", function: "Foam Booster/Thickener" },
  { trade_name: "Sodium Cocoyl Isethionate", inci: "Sodium Cocoyl Isethionate", cas: "61789-32-0", function: "Surfactant/Cleansing" },
  { trade_name: "SCI", inci: "Sodium Cocoyl Isethionate", cas: "61789-32-0", function: "Surfactant/Cleansing" },
  { trade_name: "Disodium Laureth Sulfosuccinate", inci: "Disodium Laureth Sulfosuccinate", cas: "39354-45-5", function: "Mild Surfactant" },
  { trade_name: "Sodium Cocoyl Glutamate", inci: "Sodium Cocoyl Glutamate", cas: "68187-32-6", function: "Mild Surfactant" },
  { trade_name: "Sodium Lauroyl Sarcosinate", inci: "Sodium Lauroyl Sarcosinate", cas: "137-16-6", function: "Mild Surfactant" },

  // ── pH Adjusters ──────────────────────────────────────────────────────────────
  { trade_name: "Triethanolamine", inci: "Triethanolamine", cas: "102-71-6", function: "pH Adjuster/Emulsifier" },
  { trade_name: "TEA", inci: "Triethanolamine", cas: "102-71-6", function: "pH Adjuster" },
  { trade_name: "Sodium Hydroxide", inci: "Sodium Hydroxide", cas: "1310-73-2", function: "pH Adjuster" },
  { trade_name: "Potassium Hydroxide", inci: "Potassium Hydroxide", cas: "1310-58-3", function: "pH Adjuster" },
  { trade_name: "Citric Acid", inci: "Citric Acid", cas: "77-92-9", function: "pH Adjuster/Chelating Agent" },
  { trade_name: "Sodium Citrate", inci: "Sodium Citrate", cas: "68-04-2", function: "pH Buffer/Chelating Agent" },
  { trade_name: "Tartaric Acid", inci: "Tartaric Acid", cas: "87-69-4", function: "pH Adjuster/AHA" },

  // ── Chelating / Sequestering Agents ──────────────────────────────────────────
  { trade_name: "EDTA", inci: "Tetrasodium EDTA", cas: "64-02-8", function: "Chelating Agent" },
  { trade_name: "Tetrasodium EDTA", inci: "Tetrasodium EDTA", cas: "64-02-8", function: "Chelating Agent" },
  { trade_name: "Disodium EDTA", inci: "Disodium EDTA", cas: "139-33-3", function: "Chelating Agent" },
  { trade_name: "Sodium Gluconate", inci: "Sodium Gluconate", cas: "527-07-1", function: "Chelating Agent/Humectant" },
  { trade_name: "Phytic Acid", inci: "Phytic Acid", cas: "83-86-3", function: "Chelating Agent/Antioxidant" },

  // ── Antioxidants ──────────────────────────────────────────────────────────────
  { trade_name: "BHT", inci: "BHT", cas: "128-37-0", function: "Antioxidant" },
  { trade_name: "BHA", inci: "BHA", cas: "25013-16-5", function: "Antioxidant" },
  { trade_name: "Tocopherol", inci: "Tocopherol", cas: "59-02-9", function: "Antioxidant/Vitamin E" },
  { trade_name: "Vitamin E", inci: "Tocopherol", cas: "59-02-9", function: "Antioxidant" },
  { trade_name: "Tocopheryl Acetate", inci: "Tocopheryl Acetate", cas: "58-95-7", function: "Antioxidant/Vitamin E" },
  { trade_name: "Vitamin E Acetate", inci: "Tocopheryl Acetate", cas: "58-95-7", function: "Antioxidant" },
  { trade_name: "Rosemary Extract", inci: "Rosmarinus Officinalis Leaf Extract", cas: "84604-14-8", function: "Antioxidant/Preservative Booster" },
  { trade_name: "Ascorbic Acid", inci: "Ascorbic Acid", cas: "50-81-7", function: "Antioxidant/Vitamin C/Brightening" },
  { trade_name: "Vitamin C", inci: "Ascorbic Acid", cas: "50-81-7", function: "Antioxidant/Brightening" },
  { trade_name: "Sodium Ascorbyl Phosphate", inci: "Sodium Ascorbyl Phosphate", cas: "66170-10-3", function: "Antioxidant/Brightening" },
  { trade_name: "Ascorbyl Glucoside", inci: "Ascorbyl Glucoside", cas: "129499-78-1", function: "Antioxidant/Brightening" },

  // ── Active Ingredients / Anti-aging ──────────────────────────────────────────
  { trade_name: "Retinol", inci: "Retinol", cas: "68-26-8", function: "Anti-aging/Skin Renewal" },
  { trade_name: "Vitamin A", inci: "Retinol", cas: "68-26-8", function: "Anti-aging" },
  { trade_name: "Retinyl Palmitate", inci: "Retinyl Palmitate", cas: "79-81-2", function: "Anti-aging" },
  { trade_name: "Niacinamide", inci: "Niacinamide", cas: "98-92-0", function: "Anti-aging/Brightening/Sebum Control" },
  { trade_name: "Vitamin B3", inci: "Niacinamide", cas: "98-92-0", function: "Anti-aging/Brightening" },
  { trade_name: "Resveratrol", inci: "Resveratrol", cas: "501-36-0", function: "Antioxidant/Anti-aging" },
  { trade_name: "Adenosine", inci: "Adenosine", cas: "58-61-7", function: "Anti-aging/Skin Conditioning" },
  { trade_name: "Argireline", inci: "Acetyl Hexapeptide-3", cas: "616204-22-9", function: "Anti-aging/Peptide" },
  { trade_name: "Acetyl Hexapeptide-8", inci: "Acetyl Hexapeptide-8", cas: "616204-22-9", function: "Anti-aging/Peptide" },
  { trade_name: "Matrixyl 3000", inci: "Palmitoyl Tripeptide-1 (and) Palmitoyl Tetrapeptide-7", cas: "147732-56-7", supplier: "Sederma", function: "Anti-aging/Peptide" },
  { trade_name: "Matrixyl", inci: "Palmitoyl Pentapeptide-4", cas: "214047-00-4", supplier: "Sederma", function: "Anti-aging/Peptide" },
  { trade_name: "Haloxyl", inci: "Palmitoyl Tetrapeptide-7 (and) Palmitoyl Oligopeptide", cas: "-", supplier: "Sederma", function: "Dark Circle Reducer" },
  { trade_name: "Leuphasyl", inci: "Acetyl Tyrosinol-3 (and) Acetyl Glutamyl Heptapeptide-3", cas: "-", supplier: "Lipotec", function: "Anti-aging/Peptide" },
  { trade_name: "EGF", inci: "Sh-Oligopeptide-1", cas: "62253-63-8", function: "Anti-aging/Growth Factor" },
  { trade_name: "Copper Peptide GHK-Cu", inci: "Copper Tripeptide-1", cas: "49557-75-7", function: "Anti-aging/Wound Healing" },
  { trade_name: "Alpha-Arbutin", inci: "Alpha-Arbutin", cas: "84380-01-8", function: "Brightening/Whitening" },
  { trade_name: "Kojic Acid", inci: "Kojic Acid", cas: "501-30-4", function: "Brightening/Whitening" },
  { trade_name: "Azelaic Acid", inci: "Azelaic Acid", cas: "123-99-9", function: "Brightening/Anti-acne" },
  { trade_name: "Salicylic Acid", inci: "Salicylic Acid", cas: "69-72-7", function: "Exfoliant/Anti-acne/BHA" },
  { trade_name: "Mandelic Acid", inci: "Mandelic Acid", cas: "90-64-2", function: "Exfoliant/AHA" },
  { trade_name: "Glycolic Acid", inci: "Glycolic Acid", cas: "79-14-1", function: "Exfoliant/AHA" },
  { trade_name: "Bakuchiol", inci: "Bakuchiol", cas: "10309-37-2", function: "Anti-aging/Retinol Alternative" },
  { trade_name: "Ceramide NP", inci: "Ceramide NP", cas: "100403-19-8", function: "Skin Barrier/Moisturizer" },
  { trade_name: "Ceramide AP", inci: "Ceramide AP", cas: "1246298-63-4", function: "Skin Barrier/Moisturizer" },
  { trade_name: "Ceramide EOP", inci: "Ceramide EOP", cas: "123999-67-7", function: "Skin Barrier/Moisturizer" },

  // ── Skin Conditioning / Proteins ─────────────────────────────────────────────
  { trade_name: "Hydrolyzed Collagen", inci: "Hydrolyzed Collagen", cas: "9015-54-7", function: "Skin Conditioning/Film Former" },
  { trade_name: "Hydrolyzed Silk", inci: "Hydrolyzed Silk", cas: "96690-41-4", function: "Skin/Hair Conditioning" },
  { trade_name: "Hydrolyzed Wheat Protein", inci: "Hydrolyzed Wheat Protein", cas: "94350-06-8", function: "Hair/Skin Conditioning" },
  { trade_name: "Hydrolyzed Keratin", inci: "Hydrolyzed Keratin", cas: "69430-36-0", function: "Hair Conditioning" },
  { trade_name: "Hydrolyzed Soy Protein", inci: "Hydrolyzed Soy Protein", cas: "68607-88-5", function: "Skin/Hair Conditioning" },
  { trade_name: "Hydrolyzed Rice Protein", inci: "Hydrolyzed Rice Protein", cas: "100209-45-8", function: "Skin/Hair Conditioning" },
  { trade_name: "Collagen", inci: "Soluble Collagen", cas: "9007-34-5", function: "Skin Conditioning/Moisturizer" },

  // ── Sunscreen Filters ─────────────────────────────────────────────────────────
  { trade_name: "Titanium Dioxide", inci: "Titanium Dioxide", cas: "13463-67-7", function: "UV Filter/Physical Sunscreen" },
  { trade_name: "Zinc Oxide", inci: "Zinc Oxide", cas: "1314-13-2", function: "UV Filter/Physical Sunscreen" },
  { trade_name: "Octinoxate", inci: "Ethylhexyl Methoxycinnamate", cas: "5466-77-3", function: "UVB Filter" },
  { trade_name: "Uvinul MC80", inci: "Ethylhexyl Methoxycinnamate", cas: "5466-77-3", supplier: "BASF", function: "UVB Filter" },
  { trade_name: "Oxybenzone", inci: "Benzophenone-3", cas: "131-57-7", function: "UVB/UVA Filter" },
  { trade_name: "Avobenzone", inci: "Butyl Methoxydibenzoylmethane", cas: "70356-09-1", function: "UVA Filter" },
  { trade_name: "Parsol 1789", inci: "Butyl Methoxydibenzoylmethane", cas: "70356-09-1", supplier: "DSM", function: "UVA Filter" },
  { trade_name: "Tinosorb S", inci: "Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine", cas: "187393-00-6", supplier: "BASF", function: "Broadspectrum UV Filter" },
  { trade_name: "Tinosorb M", inci: "Methylene Bis-Benzotriazolyl Tetramethylbutylphenol", cas: "187393-00-6", supplier: "BASF", function: "Broadspectrum UV Filter" },
  { trade_name: "Mexoryl SX", inci: "Terephthalylidene Dicamphor Sulfonic Acid", cas: "90457-82-2", supplier: "L'Oreal", function: "UVA Filter" },
  { trade_name: "Uvinul A Plus", inci: "Diethylamino Hydroxybenzoyl Hexyl Benzoate", cas: "302776-68-7", supplier: "BASF", function: "UVA Filter" },
  { trade_name: "Octisalate", inci: "Ethylhexyl Salicylate", cas: "118-60-5", function: "UVB Filter" },
  { trade_name: "Homosalate", inci: "Homosalate", cas: "118-56-9", function: "UVB Filter" },
  { trade_name: "Octocrylene", inci: "Octocrylene", cas: "6197-30-4", function: "UVB Filter" },

  // ── Pigments / Colorants ──────────────────────────────────────────────────────
  { trade_name: "Iron Oxide Red", inci: "Iron Oxides (CI 77491)", cas: "1309-37-1", function: "Colorant" },
  { trade_name: "Iron Oxide Yellow", inci: "Iron Oxides (CI 77492)", cas: "51274-00-1", function: "Colorant" },
  { trade_name: "Iron Oxide Black", inci: "Iron Oxides (CI 77499)", cas: "1317-61-9", function: "Colorant" },
  { trade_name: "Mica", inci: "Mica", cas: "12001-26-2", function: "Colorant/Pearlescent" },
  { trade_name: "Talc", inci: "Talc", cas: "14807-96-6", function: "Filler/Absorbent" },
  { trade_name: "Ultramarines Blue", inci: "Ultramarines (CI 77007)", cas: "57455-37-5", function: "Colorant" },
  { trade_name: "Chromium Oxide Green", inci: "Chromium Oxide Greens (CI 77288)", cas: "1308-38-9", function: "Colorant" },

  // ── Botanical Extracts ────────────────────────────────────────────────────────
  { trade_name: "Aloe Vera", inci: "Aloe Barbadensis Leaf Juice", cas: "85507-69-3", function: "Soothing/Moisturizer" },
  { trade_name: "Aloe Vera Gel", inci: "Aloe Barbadensis Leaf Juice", cas: "85507-69-3", function: "Soothing/Moisturizer" },
  { trade_name: "Green Tea Extract", inci: "Camellia Sinensis Leaf Extract", cas: "84650-60-2", function: "Antioxidant" },
  { trade_name: "Chamomile Extract", inci: "Anthemis Nobilis Flower Extract", cas: "84649-86-5", function: "Soothing" },
  { trade_name: "Calendula Extract", inci: "Calendula Officinalis Flower Extract", cas: "84776-23-8", function: "Soothing/Anti-inflammatory" },
  { trade_name: "Licorice Extract", inci: "Glycyrrhiza Glabra Root Extract", cas: "68916-91-6", function: "Brightening/Soothing" },
  { trade_name: "Centella Asiatica", inci: "Centella Asiatica Extract", cas: "84696-21-9", function: "Soothing/Wound Healing" },
  { trade_name: "Noni Extract", inci: "Morinda Citrifolia Fruit Extract", cas: "223749-84-6", function: "Antioxidant" },
  { trade_name: "Sea Buckthorn Extract", inci: "Hippophae Rhamnoides Fruit Extract", cas: "90106-68-6", function: "Antioxidant/Emollient" },
  { trade_name: "Ginger Extract", inci: "Zingiber Officinale Root Extract", cas: "84696-15-1", function: "Antioxidant/Stimulating" },

  // ── Film Formers ──────────────────────────────────────────────────────────────
  { trade_name: "PVP", inci: "PVP", cas: "9003-39-8", function: "Film Former/Binder" },
  { trade_name: "Polyvinylpyrrolidone", inci: "PVP", cas: "9003-39-8", function: "Film Former/Binder" },
  { trade_name: "PVP/VA Copolymer", inci: "VP/VA Copolymer", cas: "25086-89-9", function: "Film Former" },
  { trade_name: "Chitosan", inci: "Chitosan", cas: "9012-76-4", function: "Film Former/Conditioning" },

  // ── Conditioning Agents / Cationic ───────────────────────────────────────────
  { trade_name: "Cetrimonium Chloride", inci: "Cetrimonium Chloride", cas: "112-02-7", function: "Conditioning/Antimicrobial" },
  { trade_name: "Behentrimonium Chloride", inci: "Behentrimonium Chloride", cas: "17301-53-0", function: "Conditioning/Detangling" },
  { trade_name: "Polyquaternium-10", inci: "Polyquaternium-10", cas: "68610-92-4", function: "Conditioning/Film Former" },
  { trade_name: "Polyquaternium-7", inci: "Polyquaternium-7", cas: "26590-05-6", function: "Conditioning/Film Former" },
  { trade_name: "Guar Hydroxypropyltrimonium Chloride", inci: "Guar Hydroxypropyltrimonium Chloride", cas: "65497-29-2", function: "Conditioning/Thickener" },

  // ── Miscellaneous ─────────────────────────────────────────────────────────────
  { trade_name: "Zinc Pyrithione", inci: "Zinc Pyrithione", cas: "13463-41-7", function: "Anti-dandruff/Preservative" },
  { trade_name: "Cyclomethicone D5", inci: "Cyclopentasiloxane", cas: "541-02-6", function: "Emollient/Carrier" },
  { trade_name: "Hydrogenated Polyisobutene", inci: "Hydrogenated Polyisobutene", cas: "61693-08-1", function: "Emollient/Viscosity Modifier" },
  { trade_name: "C12-15 Alkyl Benzoate", inci: "C12-15 Alkyl Benzoate", cas: "68411-27-8", function: "Emollient/Skin Feel" },
  { trade_name: "Finsolv TN", inci: "C12-15 Alkyl Benzoate", cas: "68411-27-8", supplier: "Innospec", function: "Emollient/Solubilizer" },
  { trade_name: "Neopentyl Glycol Diheptanoate", inci: "Neopentyl Glycol Diheptanoate", cas: "93971-72-3", function: "Emollient" },
  { trade_name: "Diisopropyl Sebacate", inci: "Diisopropyl Sebacate", cas: "7491-02-3", function: "Emollient/Skin Feel" },
  { trade_name: "Sodium Lactate", inci: "Sodium Lactate", cas: "72-17-3", function: "Humectant/pH Buffer" },
  { trade_name: "Triethanolamine", inci: "Triethanolamine", cas: "102-71-6", function: "pH Adjuster/Neutralizer" },
  { trade_name: "Aminomethyl Propanol", inci: "Aminomethyl Propanol", cas: "124-68-5", function: "pH Adjuster/Neutralizer" },
  { trade_name: "AMP", inci: "Aminomethyl Propanol", cas: "124-68-5", function: "pH Adjuster" },
  { trade_name: "Sodium Chloride", inci: "Sodium Chloride", cas: "7647-14-5", function: "Viscosity Modifier/Electrolyte" },
  { trade_name: "Salt", inci: "Sodium Chloride", cas: "7647-14-5", function: "Viscosity Modifier" },
  { trade_name: "Magnesium Sulfate", inci: "Magnesium Sulfate", cas: "7487-88-9", function: "Viscosity Modifier/Electrolyte" },
]

// Search function — matches trade name, INCI name, or CAS number
export function searchIngredients(query) {
  if (!query || query.trim().length < 2) return []
  const q = query.trim().toLowerCase()
  return ingredientDB
    .filter(item =>
      (item.trade_name || '').toLowerCase().includes(q) ||
      (item.inci || '').toLowerCase().includes(q) ||
      (item.cas || '').includes(q)
    )
    .slice(0, 10)
}
