[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install", "npm install --prefix client"]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
DATA_DIR = "/data"
